{
 "title": "Minecraft stats",
 "tags": [ "minecraft" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "player",
    "query": {
     "query": "label_values(minecraft_player_dimension,player)"
    }
   },
   {
    "name": "interval",
    "query": "15s,30s,1m,5m,10m,30m,1h,2h,6h,12h,1d"
   },
   {
    "name": "step",
    "query": "15s,30s,1m,5m,10m,30m,1h,2h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Dimensions",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "minecraft_player_dimension{player=\"$player\"}",
     "legendFormat": "{{ dimension }}"
    }
   ]
  },
  {
   "title": "Jumps",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "minecraft_player_custom{metric=\"jump\",player=\"$player\"}"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "minecraft_player_custom{metric=\"deaths\",player=\"$player\"}"
    }
   ]
  },
  {
   "title": "Times",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_player_custom{metric=~\".*time.*\", player=\"$player\"}",
     "legendFormat": "{{ metric }}"
    }
   ]
  },
  {
   "title": "Level",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "minecraft_player_custom{metric=\"xplevel\",player=\"$player\"}"
    }
   ]
  },
  {
   "title": "Killed by",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_player_killed_by{player=\"$player\"}",
     "legendFormat": "{{ entity }}"
    }
   ]
  },
  {
   "title": "XP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minecraft_player_custom{metric=\"xptotal\",player=\"$player\"}"
    }
   ]
  },
  {
   "title": "Blocks mined",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(minecraft_player_mined{player=\"$player\"}[$interval]) > 0",
     "legendFormat": "{{ item }}"
    }
   ]
  },
  {
   "title": "Blocks collected",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(minecraft_player_picked_up{player=\"$player\"}[$interval]) > 0",
     "legendFormat": "{{ item }}"
    }
   ]
  },
  {
   "title": "Items crafted",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(minecraft_player_crafted{player=\"$player\"}[$interval]) > 0",
     "legendFormat": "{{ item }}"
    }
   ]
  },
  {
   "title": "Interactions",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(minecraft_player_custom{metric=~\"(open|intera).*\",player=\"$player\"}[$interval]) > 0",
     "legendFormat": "{{ metric }}"
    }
   ]
  },
  {
   "title": "Mobs killed",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "increase(minecraft_player_killed{player=\"$player\"}[$interval]) > 0",
     "legendFormat": "{{ entity }}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minecraft_player_custom{metric=\"health\",player=\"$player\"}",
     "legendFormat": "Health"
    },
    {
     "expr": "minecraft_player_custom{metric=\"foodlevel\",player=\"$player\"}",
     "legendFormat": "Food"
    }
   ]
  },
  {
   "title": "Damage",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(minecraft_player_custom{metric=~\"damage.*\", player=\"$player\"}[$interval]) > 0",
     "legendFormat": "{{  metric }}"
    }
   ]
  },
  {
   "title": "Meters travelled",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "increase(minecraft_player_custom{metric=~\".*one_cm\",player=\"$player\"}[$interval]) / 1000",
     "legendFormat": "{{  metric }}"
    }
   ]
  }
 ]
}